
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-01T10:54:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f06e594892a70ca6e3aec70533f128a074f730cb",
 "version": "2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
